### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by neofreko** [waigo/waigo#35]
I tried to follow the guide [here](http://waigojs.com/guide.html), but failed on my first attempt on running `./start-app.js`

```
$ ./start-app.js
/Users/neofreko/Hacks/waigo-helo/start-app.js:32
})(function(err) {
  ^
TypeError: object is not a function
    at Object.<anonymous> (/Users/neofreko/Hacks/waigo-helo/start-app.js:32:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
    at startup (node.js:124:16)
    at node.js:807:3
```

Apparently we can't run `co` result as function. Instead, we should use the `catch` method

```js
#!/usr/bin/env node --harmony
"use strict";


/**
 * @fileOverview The main entry point for your Waigo application.
 */


var co = require('co'),
  waigo = require('waigo');


co(function*() {
  /*
  Initialise the Waigo framework.

  If you need to override the application source folder and/or plugins to
  be loaded then this is the place to do it.

   */
  yield waigo.init();

  /*
  Start the application.

  This loads in application configuration, runs all startup steps, sets up
  the middleware and kicks off the HTTP listener.
   */
  yield waigo.load('application').start();

}).catch(function(err) {
  if (err) {
    console.error(err.stack);
  }
});
```

There you go
```
./start-app.js
2015-04-03T08:29:45.027Z - info: Server listening in development mode on port 3000 (baseURL: http://localhost:3000)
```
Note: I'm using node v0.11.13

**Comment by hiddentao** [comment]
Seems has co has been updated recently to return a promise instead of a thunk. Thanks for spotting this.

**Comment by hiddentao** [comment]
This is fixed in v2.
